
# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE - SUPABASE
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.kgemsrnpdsihnfagqnvn
spring.datasource.password=+6?c.K6heR_xpZg
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.data-source-properties.prepareThreshold=0
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.springframework.boot.autoconfigure=DEBUG
app.cors.allowed-origins=http://localhost:5173,https://suivi-tarot-front.onrender.com
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true



# ===============================
# JWT CONFIG
# ===============================
app.jwt.secret=6658cc343b867f62e034b05bc64e0f68444d7d60be073f83cb35c84ed2e02e37
app.jwt.issuer=budget-app
app.jwt.accessTokenMinutes=240

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=ERROR
